# Generated by Django 5.0.4 on 2024-04-28 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collectings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collect',
            name='user',
            field=models.ForeignKey(db_comment='Пользователь', help_text='Пользователь', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='collect',
            name='occasion',
            field=models.ForeignKey(db_comment='Повод для сбора', help_text='Повод для сбора', on_delete=django.db.models.deletion.PROTECT, to='collectings.occasion', verbose_name='Повод для сбора'),
        ),
        migrations.AddField(
            model_name='payment',
            name='collect',
            field=models.ForeignKey(db_comment='Сбор', help_text='Сбор', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='collectings.collect', verbose_name='Сбор'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(db_comment='Пользователь', help_text='Пользователь', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
