# Generated by Django 5.0.4 on 2024-05-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectings', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает начисление'), ('waiting_for_capture', 'Ожидает списание'), ('succeeded', 'Успешно'), ('canceled', 'Отменено')], db_comment='Статус платежа', default='pending', help_text='Статус платежа', max_length=19, verbose_name='Статус платежа'),
        ),
    ]
