# Generated by Django 5.0.4 on 2024-04-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.BooleanField(db_comment='Статус платежа', default=False, help_text='Статус платежа', verbose_name='Статус платежа'),
        ),
    ]
