version: '3'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    image: postgres:16-alpine
    env_file: .env
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 3s
    ports:
      - ${DOCKER_COMPOSER_PORT_DB:-5432:5432}

  backend:
    restart: always
    build:
      context: ../
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    command: bash -c "make project-start-in-container"
    volumes:
      - media:/app/media
      - static:/app/static
      - ../src/:/app/src/
    ports:
      - 8000:8000

