# Generated by Django 5.0.4 on 2024-04-27 00:21

import autoslug.fields
import django.core.validators
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_comment='Название', help_text='Название', max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Название')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, db_comment='Slug-название', editable=False, help_text='Slug-название', max_length=100, populate_from='name', unique=True, verbose_name='Slug-название')),
            ],
            options={
                'verbose_name': 'Решаемая проблема',
                'verbose_name_plural': 'Решаемые проблемы',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_comment='Название', help_text='Название', max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Название')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, db_comment='Slug-название', editable=False, help_text='Slug-название', max_length=100, populate_from='name', unique=True, verbose_name='Slug-название')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_comment='Название', help_text='Название', max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Название')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, db_comment='Slug-название', editable=False, help_text='Slug-название', max_length=100, populate_from='name', unique=True, verbose_name='Slug-название')),
                ('cover', django_resized.forms.ResizedImageField(crop=None, db_comment='Обложка', force_format=None, help_text='Обложка', keep_meta=True, quality=-1, scale=None, size=(1500, 1500), upload_to='covers/', verbose_name='Обложка')),
                ('description', models.TextField(db_comment='Описание', help_text='Описание', validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Описание')),
                ('problems', models.ManyToManyField(help_text='Решаемые проблемы', to='organizations.problem', verbose_name='Решаемые проблемы')),
                ('regions', models.ManyToManyField(help_text='Регионы', to='organizations.region', verbose_name='Регионы')),
            ],
            options={
                'verbose_name': 'Некоммерческая организация',
                'verbose_name_plural': 'Некоммерческие организации',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
    ]
